version: '3.9'

services:
  postgres:
    container_name: postgres-doctor-container
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped