ALTER TABLE appointment
    ADD CONSTRAINT APPOINTMENT_PERSON_FK
        FOREIGN KEY (user_id) REFERENCES person (id),
    ADD CONSTRAINT APPOINTMENT_SCHEDULE_FK
        FOREIGN KEY (schedule_id) REFERENCES schedule (id);